#!/bin/bash

case "${DOCKER_TAG}" in
     bionic|focal|groovy|hirsute|impish|jammy|kinetic)
         vendor="ubuntu"
         ;;
     *)
         vendor="debian"
         ;;
esac

docker build --build-arg vendor=${vendor} --build-arg release=${DOCKER_TAG} -f ${DOCKERFILE_PATH} -t ${IMAGE_NAME} .
